text

diff --git a/.github/workflows/daily-build.yml b/.github/workflows/daily-build.yml
--- a/.github/workflows/daily-build.yml
+++ b/.github/workflows/daily-build.yml
@@ -39,6 +39,7 @@ jobs:
           echo "dummy" >> dummy_folder/text-${{ matrix.pyver }}.txt
           filename=$(ls dummy_folder/)
           echo "filename=$filename" >> "$GITHUB_OUTPUT"
+
           # echo ${PYTHON_VERSION}
           # echo ${PLAT_NAME}
           # echo ${DOCKER_TAG}
@@ -54,45 +55,52 @@ jobs:
           path: dummy_folder/${{ steps.build.outputs.filename }}
           retention-days: 1
 
-  # windows-build:
-  #   strategy:
-  #     matrix:
-  #       pyver: ['3.8', '3.9', '3.10', '3.11', '3.12']
-  #   runs-on: windows-latest
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
-  #     - name: Set up python
-  #       uses: actions/setup-python@v4
-  #       with:
-  #         python-version: ${{ matrix.pyver }}
-  #     - name: Install python packages
-  #       run: |
-  #         pip install pybind11 wheel
-  #     - uses: Jimver/cuda-toolkit@v0.2.11
-  #       id: cuda-toolkit
-  #       with:
-  #         cuda: '12.1.0'
-  #         use-github-cache: false
-  #     - name: Build wheel
-  #       run: |
-  #         mkdir build
-  #         cd build
-  #         # https://github.com/pypa/setuptools/issues/1631
-  #         pip install -U setuptools
-  #         ..\builder\windows\generate.ps1
-  #         cmake --build . --config Release -- /m /v:q
-  #         if (-Not $?) {
-  #           echo "build failed"
-  #           exit 1
-  #         }
-  #         cmake --install . --config Release
-  #         cd ..
-  #         rm build -Force -Recurse
-  #         python setup.py bdist_wheel -d build/wheel
-  #     - name: Upload Artifacts
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         if-no-files-found: error
-  #         path: build/wheel/*
-  #         retention-days: 1
+  windows-build:
+    strategy:
+      matrix:
+        pyver: ['3.8', '3.9', '3.10', '3.11', '3.12']
+    runs-on: windows-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+      # - name: Set up python
+      #   uses: actions/setup-python@v4
+      #   with:
+      #     python-version: ${{ matrix.pyver }}
+      # - name: Install python packages
+      #   run: |
+      #     pip install pybind11 wheel
+      # - uses: Jimver/cuda-toolkit@v0.2.11
+      #   id: cuda-toolkit
+      #   with:
+      #     cuda: '12.1.0'
+      #     use-github-cache: false
+      - name: Build wheel
+        id: build
+        run: |
+          mkdir dummy_folder
+          echo "dummy" >> dummy_folder/text-${{ matrix.pyver }}.win.txt
+          $filename = Get-ChildItem dummy_folder -Name
+          echo "$filename=$filename" >> "$env:GITHUB_OUTPUT"
+
+          # mkdir build
+          # cd build
+          # # https://github.com/pypa/setuptools/issues/1631
+          # pip install -U setuptools
+          # ..\builder\windows\generate.ps1
+          # cmake --build . --config Release -- /m /v:q
+          # if (-Not $?) {
+          #   echo "build failed"
+          #   exit 1
+          # }
+          # cmake --install . --config Release
+          # cd ..
+          # rm build -Force -Recurse
+          # python setup.py bdist_wheel -d build/wheel
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          if-no-files-found: error
+          name: ${{ steps.build.outputs.filename }}
+          path: dummy_folder/${{ steps.build.outputs.filename }}
+          retention-days: 1
